# -*- coding: utf-8 -*-

# Project Statuses
PROJECT_STATUS_IN_PROGRESS = 'قيد التنفيذ'
PROJECT_STATUS_COMPLETED = 'مكتمل'
PROJECT_STATUS_ON_HOLD = 'معلق'
PROJECT_STATUS_CANCELLED = 'ملغي'

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_IN_PROGRESS, PROJECT_STATUS_IN_PROGRESS),
    (PROJECT_STATUS_COMPLETED, PROJECT_STATUS_COMPLETED),
    (PROJECT_STATUS_ON_HOLD, PROJECT_STATUS_ON_HOLD),
    (PROJECT_STATUS_CANCELLED, PROJECT_STATUS_CANCELLED),
]

# Item Statuses
ITEM_STATUS_ACTIVE = 'نشط'
ITEM_STATUS_COMPLETED = 'مكتمل'
ITEM_STATUS_ON_HOLD = 'معلق'

ITEM_STATUS_CHOICES = [
    (ITEM_STATUS_ACTIVE, ITEM_STATUS_ACTIVE),
    (ITEM_STATUS_COMPLETED, ITEM_STATUS_COMPLETED),
    (ITEM_STATUS_ON_HOLD, ITEM_STATUS_ON_HOLD),
]

# Invoice Statuses
INVOICE_STATUS_NEW = 'جديد'
INVOICE_STATUS_UNDER_REVIEW = 'تحت المراجعة'
INVOICE_STATUS_APPROVED = 'معتمد'
INVOICE_STATUS_PARTIALLY_PAID = 'مدفوع جزئياً'
INVOICE_STATUS_FULLY_PAID = 'مدفوع بالكامل'
INVOICE_STATUS_CANCELLED = 'ملغي'