"""add notes to contractor

Revision ID: 003_add_notes_to_contractor
Revises: 002_add_vat_percent
Create Date: 2025-09-07 20:41:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_notes_to_contractor'
down_revision = '002_add_vat_percent'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###