"""empty message

Revision ID: 22a5c9c70461
Revises: 003_add_notes_to_contractor
Create Date: 2025-10-12 19:20:19.298485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a5c9c70461'
down_revision = '003_add_notes_to_contractor'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_audit_log_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.create_index('idx_cost_detail_contractor_id', ['contractor_id'], unique=False)
        batch_op.create_index('idx_cost_detail_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('idx_item_contractor_id', ['contractor_id'], unique=False)
        batch_op.create_index('idx_item_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_invoice_id', ['invoice_id'], unique=False)

    with op.batch_alter_table('payment_distribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_distribution_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_distribution_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_distribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_distribution_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_distribution_invoice_item_id'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_invoice_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('idx_item_project_id')
        batch_op.drop_index('idx_item_contractor_id')

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_index('idx_cost_detail_item_id')
        batch_op.drop_index('idx_cost_detail_contractor_id')

    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_user_id')
        batch_op.drop_index('idx_audit_log_item_id')

    op.drop_table('audit_log')
    op.drop_table('user_project')
    # ### end Alembic commands ###
