"""Add status to CostDetail model

Revision ID: 299d394b9b17
Revises: 80a7451511fa
Create Date: 2025-08-25 12:23:11.639704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299d394b9b17'
down_revision = '80a7451511fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
