"""Update item model logic and remove execution_method

Revision ID: 6316c73746ab
Revises: d8e6ba4f38af
Create Date: 2025-08-31 12:58:40.720463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6316c73746ab'
down_revision = 'd8e6ba4f38af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('execution_method')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_payment_invoice_item_id', ['invoice_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_invoice_item_id')
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
