"""Add full fields to CostDetail model

Revision ID: 80a7451511fa
Revises: 
Create Date: 2025-08-25 11:59:57.881556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a7451511fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('total_cost')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('quantity')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
