"""Final schema with cost details link

Revision ID: 824c1c189409
Revises: 
Create Date: 2025-09-02 09:56:32.330232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824c1c189409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_detail_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cost_detail', ['cost_detail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost_detail_id')

    # ### end Alembic commands ###
