"""Add indexes to improve query performance

Revision ID: 854d54169ebd
Revises: 2d3c54bd4e66
Create Date: 2025-08-27 11:00:00.569737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854d54169ebd'
down_revision = '2d3c54bd4e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_audit_log_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.create_index('idx_cost_detail_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('idx_item_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_payment_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_project_id')
        batch_op.drop_index('idx_payment_item_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('idx_item_project_id')

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_index('idx_cost_detail_item_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_user_id')
        batch_op.drop_index('idx_audit_log_item_id')

    # ### end Alembic commands ###
