"""Generate initial schema for all tables

Revision ID: 96c9bc50c740
Revises: 
Create Date: 2025-09-01 10:40:04.251422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c9bc50c740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.create_index('idx_cost_detail_contractor_id', ['contractor_id'], unique=False)
        batch_op.create_index('idx_cost_detail_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('execution_method')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_invoice_item_id', ['invoice_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_invoice_item_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_index('idx_cost_detail_item_id')
        batch_op.drop_index('idx_cost_detail_contractor_id')

    op.drop_table('cost_detail')
    # ### end Alembic commands ###
