"""Add PO, disbursement numbers and invoice type

Revision ID: 9d7a3b0ab733
Revises: a2079bec426c
Create Date: 2025-09-06 11:33:53.855194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7a3b0ab733'
down_revision = 'a2079bec426c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disbursement_order_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')
        batch_op.drop_column('invoice_type')

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_column('disbursement_order_number')
        batch_op.drop_column('purchase_order_number')

    # ### end Alembic commands ###
