"""Add payment distribution feature

Revision ID: a2079bec426c
Revises: 824c1c189409
Create Date: 2025-09-03 12:26:23.184238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2079bec426c'
down_revision = '824c1c189409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_item.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_distribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_distribution_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_distribution_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_invoice_item_id'))
        batch_op.drop_constraint(batch_op.f('fk_payment_invoice_item_id'), type_='foreignkey')
        batch_op.drop_column('invoice_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_invoice_item_id'), 'invoice_item', ['invoice_item_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_payment_invoice_item_id'), ['invoice_item_id'], unique=False)

    with op.batch_alter_table('payment_distribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_distribution_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_distribution_invoice_item_id'))

    op.drop_table('payment_distribution')
    # ### end Alembic commands ###
