"""Add main contractor relationship to Item model

Revision ID: ba9c6b63cd66
Revises: d67d9b27afe2
Create Date: 2025-08-28 18:10:59.014171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9c6b63cd66'
down_revision = 'd67d9b27afe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractor_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_item_contractor_id', ['contractor_id'], unique=False)
        batch_op.create_foreign_key(None, 'contractor', ['contractor_id'], ['id'])
        batch_op.drop_column('contractor')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('cost_detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('cost_detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_item_contractor_id')
        batch_op.drop_column('contractor_id')

    # ### end Alembic commands ###
