"""Add vat_percent to cost_detail

Revision ID: c5ee3d82a4d1
Revises: 4132b1b3e241
Create Date: 2025-09-07 14:15:11.274839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ee3d82a4d1'
down_revision = '4132b1b3e241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_percent', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_column('vat_percent')

    # ### end Alembic commands ###