"""Implement detailed contractor and payment structure

Revision ID: d67d9b27afe2
Revises: 73f931d774d7
Create Date: 2025-08-28 17:40:49.271725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67d9b27afe2'
down_revision = '73f931d774d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_order', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_order', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('contractor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'غير مدفوع'::character varying"))
        batch_op.create_index('idx_cost_detail_contractor_id', ['contractor_id'], unique=False)
        batch_op.create_foreign_key(None, 'contractor', ['contractor_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_detail_id', sa.Integer(), nullable=False))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_payment_cost_detail_id', ['cost_detail_id'], unique=False)
        batch_op.create_foreign_key(None, 'cost_detail', ['cost_detail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_payment_cost_detail_id')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cost_detail_id')

    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_cost_detail_contractor_id')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'غير مدفوع'::character varying"))
        batch_op.drop_column('contractor_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_order')
        batch_op.drop_column('purchase_order')

    op.drop_table('contractor')
    # ### end Alembic commands ###
