"""Add invoice_item_id to Payment model and clean up old fields

Revision ID: d8e6ba4f38af
Revises: d57c7ec5dd05 
Create Date: 2025-08-31 09:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e6ba4f38af' # << تأكد من أن هذا الرقم يطابق اسم ملفك
down_revision = 'd57c7ec5dd05' # << هذا هو رقم المراجعة السابقة


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # الخطوة 1: حذف الأعمدة والقيود القديمة من جدول الدفعات
    with op.batch_alter_table('payment', schema=None) as batch_op:
        # أولاً، نحذف القيد (المفتاح الأجنبي) الذي يسبب المشكلة
        batch_op.drop_constraint('payment_cost_detail_id_fkey', type_='foreignkey')
        # الآن يمكننا حذف العمود بأمان
        batch_op.drop_column('cost_detail_id')
        
        # حذف الأعمدة القديمة الأخرى
        batch_op.drop_column('item_id')
        batch_op.drop_column('project_id')

    # الخطوة 2: الآن بعد إزالة الاعتمادية، يمكننا حذف جدول تفاصيل التكلفة
    op.drop_table('cost_detail')

    # الخطوة 3: إضافة العمود الجديد والعلاقة الجديدة لجدول الدفعات
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_invoice_item_id', 'invoice_item', ['invoice_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # عكس عملية الإضافة
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_invoice_item_id', type_='foreignkey')
        batch_op.drop_column('invoice_item_id')

    # إعادة إنشاء جدول تفاصيل التكلفة
    op.create_table('cost_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    # ... يمكنك إضافة باقي الأعمدة القديمة هنا إذا أردت أن تكون قادراً على التراجع بشكل كامل
    sa.PrimaryKeyConstraint('id', name='cost_detail_pkey')
    )
    
    # إعادة إنشاء الأعمدة القديمة في جدول الدفعات
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payment_cost_detail_id_fkey', 'cost_detail', ['cost_detail_id'], ['id'])

    # ### end Alembic commands ###