"""Add invoice_item_id to Payment model

Revision ID: d8e6ba4f38af
Revises: d57c7ec5dd05
Create Date: 2025-08-31 12:03:23.235909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e6ba4f38af'
down_revision = 'd57c7ec5dd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cost_detail_contractor_id'))
        batch_op.drop_index(batch_op.f('idx_cost_detail_item_id'))

    op.drop_table('cost_detail')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_payment_cost_detail_id'))
        batch_op.drop_index(batch_op.f('idx_payment_item_id'))
        batch_op.drop_index(batch_op.f('idx_payment_project_id'))
        batch_op.create_index('idx_payment_invoice_item_id', ['invoice_item_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('payment_item_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_cost_detail_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoice_item', ['invoice_item_id'], ['id'])
        batch_op.drop_column('project_id')
        batch_op.drop_column('cost_detail_id')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payment_cost_detail_id_fkey'), 'cost_detail', ['cost_detail_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payment_item_id_fkey'), 'item', ['item_id'], ['id'])
        batch_op.drop_index('idx_payment_invoice_item_id')
        batch_op.create_index(batch_op.f('idx_payment_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_cost_detail_id'), ['cost_detail_id'], unique=False)
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('invoice_item_id')

    op.create_table('cost_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'غير مدفوع'::character varying"), autoincrement=False, nullable=True),
    sa.Column('purchase_order', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_order', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), server_default=sa.text("'دفعة واحدة'::character varying"), autoincrement=False, nullable=False),
    sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], name=op.f('cost_detail_contractor_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('cost_detail_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cost_detail_pkey'))
    )
    with op.batch_alter_table('cost_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cost_detail_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cost_detail_contractor_id'), ['contractor_id'], unique=False)

    # ### end Alembic commands ###
